  0%|          | 0/2 [00:00<?, ?it/s]  0%|          | 0/2 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1487, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 609, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_meta_registrations.py", line 2706, in meta_index_Tensor
    nonzero = index.nonzero()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1487, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 531, in nonzero
    raise DynamicOutputShapeException(func)
torch._subclasses.fake_tensor.DynamicOutputShapeException: aten.nonzero.default

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1337, in get_fake_value
    return wrap_fake_exception(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 916, in wrap_fake_exception
    return fn()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1338, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1410, in run_node
    raise RuntimeError(fn_str + str(e)).with_traceback(e.__traceback__) from e
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1397, in run_node
    return node.target(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1487, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 609, in index_tensor
    out = meta_index_Tensor(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_meta_registrations.py", line 2706, in meta_index_Tensor
    nonzero = index.nonzero()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1250, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 1487, in dispatch
    op_impl_out = op_impl(self, func, *args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 531, in nonzero
    raise DynamicOutputShapeException(func)
RuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., size=(2, 114615892), dtype=torch.int64), (slice(None, None, None), FakeTensor(..., size=(114615892,), dtype=torch.bool))), **{}):
aten.nonzero.default

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/u/mdshoque/Project/isplib-release-candidate/iSpLib/tests/cpu/gcn-compile.py", line 124, in <module>
    run_all()
  File "/u/mdshoque/Project/isplib-release-candidate/iSpLib/tests/cpu/gcn-compile.py", line 108, in run_all
    d = train_GCN()
  File "/u/mdshoque/Project/isplib-release-candidate/iSpLib/tests/cpu/gcn-compile.py", line 80, in train_GCN
    out = model(data.x, data.edge_index, data.edge_weight)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 490, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 133, in _fn
    return fn(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 389, in _convert_frame_assert
    return _compile(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 569, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 491, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 458, in transform
    tracer.run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2074, in run
    super().run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/nn_module.py", line 331, in call_function
    return tx.inline_user_function_return(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1155, in CALL_FUNCTION_EX
    self.call_function(fn, argsvars.items, kwargsvars.items)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 307, in call_function
    return super().call_function(tx, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1115, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 562, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 261, in call_function
    return super().call_function(tx, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 598, in inline_user_function_return
    result = InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2179, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 2286, in inline_call_
    tracer.run()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 724, in run
    and self.step()
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 688, in step
    getattr(self, inst.opname)(inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 392, in wrapper
    return inner_fn(self, inst)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 168, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/builtin.py", line 570, in call_function
    return wrap_fx_proxy(tx, proxy, **options)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1187, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 1274, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1354, in get_fake_value
    unimplemented(f"dynamic shape operator: {cause.func}")
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/_dynamo/exc.py", line 172, in unimplemented
    raise Unsupported(msg)
torch._dynamo.exc.Unsupported: dynamic shape operator: aten.nonzero.default

from user code:
   File "/u/mdshoque/Project/isplib-release-candidate/iSpLib/tests/cpu/gcn-compile.py", line 56, in forward
    x = self.conv1(x, edge_index, edge_weight)
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/tmp/mdshoque_pyg/tmpl6kn92ho.py", line 228, in forward
    edge_index, edge_weight = gcn_norm(  # yapf: disable
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 91, in gcn_norm
    edge_index, edge_weight = add_remaining_self_loops(
  File "/u/mdshoque/.conda/envs/py393/lib/python3.9/site-packages/torch_geometric/utils/loop.py", line 370, in add_remaining_self_loops
    edge_index = torch.cat([edge_index[:, mask], loop_index], dim=1)


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

